# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.7.dev0+g0c2b02f.d20230223'
__version_tuple__ = version_tuple = (0, 0, 7, 'dev0', 'g0c2b02f.d20230223')
